version: '3.4'

services:
  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "80:80"   
  #   depends_on: 
  #     - mysql
  #     - ruby
  #   environment:
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}    
  ruby:
    build:
      context: .
      dockerfile: Dockerfile.passenger
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/siphon
    ports:
      - "3000:3000"   
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}    
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"      
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_DATABASE: siphon_prod 