version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on: 
      - mysql
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"      
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_DATABASE: siphon_prod      