version: '3.4'

services:
  passenger:
    build:
      context: .
      dockerfile: Dockerfile.passenger
    ports:
      - "3000:3000"    
    depends_on: 
      - mysql
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}    
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"      
    healthcheck:
      interval: 30s
      timeout: 10s
      retries: 5 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}     
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_DATABASE: siphon_prod 